#set -g default-terminal "screen-256color"
# Forzar a tmux a usar el perfil de la TTY de Linux
set -g default-terminal "screen"


# 1. Mover la barra de estado a la parte superior de la pantalla
#set -g status-position top

# 2. Configurar los colores base de la barra (Fondo gris apagado, texto negro)
# En la TTY, 'color8' suele ser gris oscuro y 'color7' gris claro.
# Si tu TTY los invierte, puedes usar 'black' y 'white'.
#set -g status-style bg=color0,fg=color8,bold,reverse
set -g status-style bg=color0,fg=white

# Color de la barra cuando tmux hace una pregunta o muestra un mensaje
# Fondo gris oscuro (color8) forzado con bold, letras blancas brillantes (color15)
#set -g message-style bg=color15,fg=black

# 3. Formato de las ventanas activas e inactivas (Pestañas)
# Ventana actual/activa: Texto negro con fondo gris claro para resaltar
set-window-option -g window-status-current-style bg=color0,fg=color15
set-window-option -g window-status-current-format " #[bold]#I:#W#F "

# Ventanas inactivas: Texto gris claro sobre el fondo gris oscuro de la barra
set-window-option -g window-status-style bg=color8,fg=color0,reverse,bold
set-window-option -g window-status-format " #I:#W#F "

# 4. Configurar la información de los laterales
#set -g status-left-length 20
set -g status-left-style bg=color8,fg=color0,reverse,bold   # Fondo gris oscuro, texto gris claro brillante
set -g status-left " #[bold][#S] "           # Muestra el nombre de la sesión

set -g status-right-style bg=color8,fg=color0,reverse,bold   # Fondo gris oscuro, texto gris claro brillante
set -g status-right " %R │ %a %d-%m-%Y "     # Muestra la hora y fecha de forma limpia

# 5. Bordes de los paneles divididos (Para que no brillen en verde)
#set -g pane-border-style fg=color8           # Borde del panel inactivo
set -g pane-border-style bg=color8,fg=color0,reverse,bold

set -g pane-active-border-style bg=color0,fg=color15    # Borde del panel donde estás parado



# 1. Activar el modo Vi para el historial y scroll (h, j, k, l)
set-window-option -g mode-keys vi

# 2. Moverte entre paneles divididos usando Prefix + h, j, k, l
bind h select-pane -L   # Moverse al panel de la izquierda
bind j select-pane -D   # Moverse al panel de abajo
bind k select-pane -U   # Moverse al panel de arriba
bind l select-pane -R   # Moverse al panel de la derecha

# 3. (Opcional) Hacer divisiones de pantalla más intuitivas
bind v split-window -h  # División vertical (Prefix + v)
bind s split-window -v  # División horizontal (Prefix + s)

# Cerrar el panel actual sin pedir confirmación (Prefix + x)
bind-key x kill-pane

# Cerrar la pestaña/ventana actual sin pedir confirmación (Prefix + &)
bind-key & kill-window

